# Macro vs. Microclimate

First, we need to load ERA5 data and logger data:

```{r}
logger.temp <- read.csv("./DATASETS/rawtemp_min.csv", header = TRUE)

ERA5.temp <- read.csv("./DATASETS/ERA5_raw_hour.csv", header = TRUE)

mcera5.temp <- read.csv("./DATASETS/mcera5_raw.csv", header = TRUE)

weatherstations.temp <- read.csv("./DATASETS/ws_hourlydata.csv", header = TRUE)
```

... and some packages:

```{r}
library(lubridate)
library(dplyr)
library(ggplot2)
```

Logger data is at a 15-min resolution, but ERA5 data is at an hourly resolution. Let's downscale logger data to 1-hour.

```{r}
logger.temp$hour <- hour(as.POSIXct(logger.temp$time, format = "%T"))

logger.temp <- logger.temp %>%
  group_by(site, Plot, location, Date, hour) %>%
  summarise(
loggertemp = (mean(Temp)))

logger.temp$time <- paste(logger.temp$hour, ":00:00", sep="")

logger.temp$datetime <- paste(logger.temp$Date, logger.temp$time)

logger.temp$datetime <- as.POSIXct(logger.temp$datetime)

logger.temp <- dplyr::rename(logger.temp,
    date = Date)
```

Merge all datasets:

```{r}
ERA5.temp$datetime <- paste(ERA5.temp$date, ERA5.temp$time) 

ERA5.temp$hour <- hour(ERA5.temp$datetime)

mcera5.temp$hour <- hour(mcera5.temp$datetime)

weatherstations.temp$hour <- hour(weatherstations.temp$datetime)

temp <- merge(logger.temp, ERA5.temp, by = c("site", "datetime"))

rm(logger.temp)
rm(logger.temp.2)
rm(ERA5.temp)
rm(mcera5.temp)
rm(weatherstations.temp)
```

Figure:

```{r}
arville <- temp[which(temp$site == "Arville"),]

onecoldweek <- seq(as.POSIXct('2021-1-1 00:00:00'),as.POSIXct('2021-1-8 00:00:00'), by = '1 hour')

arville.week.cold <- arville[arville$datetime %in% onecoldweek,]

arville.week.cold$datetime <- paste(arville.week.cold$date.x, arville.week.cold$time.x)

#macroclimate.arville.cold.meanair <- aggregate(arville.week.cold$air_meantemp, by = list(arville.week.cold$datetime), FUN = mean)

#macroclimate.arville.cold.maxair <- aggregate(arville.week.cold$air_maxtemp, by = list(arville.week.cold$datetime), FUN = max)

#macroclimate.arville.cold.minair <- aggregate(arville.week.cold$air_mintemp, by = list(arville.week.cold$datetime), FUN = min)

#macroclimate.arville.cold.meansoil <- aggregate(arville.week.cold$soil_meantemp, by = list(arville.week.cold$datetime), FUN = mean)

#macroclimate.arville.cold <- cbind(macroclimate.arville.cold.meanair, macroclimate.arville.cold.maxair, macroclimate.arville.cold.minair, macroclimate.arville.cold.meansoil)

#macroclimate.arville.cold <- macroclimate.arville.cold[,c(1,2,4,6, 8)]

#names(macroclimate.arville.cold) <- c("Date", "mean_era5_air", "max_era5_air", "min_era5_air", "mean_era5_soil")


ggplot(arville.week.cold, aes(x = datetime)) +
geom_line(aes(y = air_meantemp), colour = "red", lwd = 2) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 1),]$loggertemp))


arville.coldplot <- ggplot(arville.week.cold, aes(x = datetime)) +
geom_line(aes(y = air_meantemp), colour = "red", lwd = 2) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 1),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 2),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 4),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 5),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 6),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 7),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 8),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 9),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 10),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 11),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 12),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 13),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 14),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 15),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 16),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 18),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 19),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 20),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 21),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 22),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 23),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 24),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 25),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 27),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 28),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 29),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 30),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 31),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 34),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 37),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 38),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 39),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.cold[which(arville.week.cold$Plot == 40),]$loggertemp)) + 
  geom_line(aes(y = air_meantemp), colour = "red", lwd = 2) +
    geom_line(aes(y = air_maxtemp), colour = "dark red", lwd = 2) +
    geom_line(aes(y = air_mintemp), colour = "orange", lwd = 2) +
   ggtitle("Arville coldest month")
  
#rm(macroclimate.arville.cold)
#rm(arville.week.cold)

# Same with warmest month (july):

onewarmweek <- seq(ymd_hms('2020-7-1 00:00:00'),ymd_hms('2020-7-8 00:00:00'), by = '1 hour')

arville.week.warm <- arville[arville$datetime %in% onewarmweek,]

macroclimate.arville.warm.meanair <- aggregate(arville.week.warm$air_meantemp, by = list(arville.week.warm$datetime), FUN = mean)

macroclimate.arville.warm.maxair <- aggregate(arville.week.warm$air_maxtemp, by = list(arville.week.warm$datetime), FUN = max)

macroclimate.arville.warm.minair <- aggregate(arville.week.warm$air_mintemp, by = list(arville.week.warm$datetime), FUN = min)

macroclimate.arville.warm.meansoil <- aggregate(arville.week.warm$soil_meantemp, by = list(arville.week.warm$datetime), FUN = mean)

macroclimate.arville.warm <- cbind(macroclimate.arville.warm.meanair, macroclimate.arville.warm.maxair, macroclimate.arville.warm.minair, macroclimate.arville.warm.meansoil)

macroclimate.arville.warm <- macroclimate.arville.warm[,c(1,2,4,6, 8)]

names(macroclimate.arville.warm) <- c("Date", "mean_era5_air", "max_era5_air", "min_era5_air", "mean_era5_soil")

arville.warmplot <- ggplot(macroclimate.arville.warm, aes(x = Date)) +
geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 1),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 2),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 4),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 5),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 6),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 7),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 8),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 9),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 10),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 11),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 12),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 13),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 14),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 15),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 16),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 18),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 19),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 20),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 21),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 22),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 23),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 24),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 25),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 27),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 28),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 29),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 30),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 31),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 34),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 37),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 38),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 39),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= arville.week.warm[which(arville.week.warm$Plot == 40),]$loggertemp)) + 
  geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
    geom_line(aes(y = max_era5_air), colour = "dark red", lwd = 2) +
    geom_line(aes(y = min_era5_air), colour = "orange", lwd = 2) +
  ggtitle("Arville warmest month")

rm(arville)
#rm(arville.week.warm)
#rm(macroclimate.arville.warm)
```

Hochwald:

```{r}
hochwald <- temp[which(temp$site == "Hochwald"),]

hochwald <- hochwald[which(hochwald$location == "a"),]

onecoldweek <- seq(ymd('2021-1-1'),ymd('2021-1-31'), by = '1 d')
hochwald$date <- as.Date(hochwald$date.x)

hochwald.week.cold <- hochwald[hochwald$date %in% onecoldweek,]

macroclimate.hochwald.cold.meanair <- aggregate(hochwald.week.cold$era5_air, by = list(hochwald.week.cold$date), FUN = mean)

macroclimate.hochwald.cold.maxair <- aggregate(hochwald.week.cold$era5_max, by = list(hochwald.week.cold$date), FUN = max)

macroclimate.hochwald.cold.minair <- aggregate(hochwald.week.cold$era5_min, by = list(hochwald.week.cold$date), FUN = min)

macroclimate.hochwald.cold.meansoil <- aggregate(hochwald.week.cold$era5_soil, by = list(hochwald.week.cold$date), FUN = mean)

macroclimate.hochwald.cold <- cbind(macroclimate.hochwald.cold.meanair, macroclimate.hochwald.cold.maxair, macroclimate.hochwald.cold.minair, macroclimate.hochwald.cold.meansoil)

macroclimate.hochwald.cold <- macroclimate.hochwald.cold[,c(1,2,4,6, 8)]

names(macroclimate.hochwald.cold) <- c("Date", "mean_era5_air", "max_era5_air", "min_era5_air", "mean_era5_soil")


hochwald.coldplot <- ggplot(macroclimate.hochwald.cold, aes(x = Date)) +
geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 1),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 2),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 3),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 4),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 5),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 7),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 8),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 9),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 10),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 11),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 12),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 14),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 16),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 17),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 18),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 19),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 20),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 21),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 22),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 23),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 24),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 25),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 26),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 27),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 28),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 29),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 30),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 31),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 32),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 33),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 35),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 36),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 37),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 38),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.cold[which(hochwald.week.cold$Plot == 40),]$loggertemp)) + 
  geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
    geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
    geom_line(aes(y = max_era5_air), colour = "dark red", lwd = 2) +
    geom_line(aes(y = min_era5_air), colour = "orange", lwd = 2) +
  ggtitle("Hochwald coldest month")
  
#rm(macroclimate.hochwald.cold)
#rm(hochwald.week.cold)

# Same with warmest month (july):

onewarmweek <- seq(ymd('2020-7-1'),ymd('2020-7-31'), by = '1 d')

hochwald.week.warm <- hochwald[hochwald$Date %in% onewarmweek,]

macroclimate.hochwald.warm.meanair <- aggregate(hochwald.week.warm$era5_air, by = list(hochwald.week.warm$Date), FUN = mean)

macroclimate.hochwald.warm.maxair <- aggregate(hochwald.week.warm$era5_max, by = list(hochwald.week.warm$Date), FUN = max)

macroclimate.hochwald.warm.minair <- aggregate(hochwald.week.warm$era5_min, by = list(hochwald.week.warm$Date), FUN = min)

macroclimate.hochwald.warm.meansoil <- aggregate(hochwald.week.warm$era5_soil, by = list(hochwald.week.warm$Date), FUN = mean)

macroclimate.hochwald.warm <- cbind(macroclimate.hochwald.warm.meanair, macroclimate.hochwald.warm.maxair, macroclimate.hochwald.warm.minair, macroclimate.hochwald.warm.meansoil)

macroclimate.hochwald.warm <- macroclimate.hochwald.warm[,c(1,2,4,6, 8)]

names(macroclimate.hochwald.warm) <- c("Date", "mean_era5_air", "max_era5_air", "min_era5_air", "mean_era5_soil")


hochwald.warmplot <- ggplot(macroclimate.hochwald.warm, aes(x = Date)) +
geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 1),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 2),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 4),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 5),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 7),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 8),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 9),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 10),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 11),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 12),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 14),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 16),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 17),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 18),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 19),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 20),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 21),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 22),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 23),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 24),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 25),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 27),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 26),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 27),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 28),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 29),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 30),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 31),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 32),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 33),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 35),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 36),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 37),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 38),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= hochwald.week.warm[which(hochwald.week.warm$Plot == 40),]$loggertemp)) + 
  geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
      geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
    geom_line(aes(y = max_era5_air), colour = "dark red", lwd = 2) +
    geom_line(aes(y = min_era5_air), colour = "orange", lwd = 2) +
  ggtitle("Hochwald warmest month")

rm(hochwald)
#rm(hochwald.week.warm)
#rm(macroclimate.hochwald.warm)
```

Vivarp:

```{r}
vivarp <- tree.temp[which(tree.temp$site == "Vivarp"),]

vivarp <- vivarp[which(vivarp$location == "a"),]

onecoldweek <- seq(ymd('2021-1-1'),ymd('2021-1-31'), by = '1 d')
vivarp$Date <- as.Date(vivarp$Date)

vivarp.week.cold <- vivarp[vivarp$Date %in% onecoldweek,]

macroclimate.vivarp.cold.meanair <- aggregate(vivarp.week.cold$era5_air, by = list(vivarp.week.cold$Date), FUN = mean)

macroclimate.vivarp.cold.maxair <- aggregate(vivarp.week.cold$era5_max, by = list(vivarp.week.cold$Date), FUN = max)

macroclimate.vivarp.cold.minair <- aggregate(vivarp.week.cold$era5_min, by = list(vivarp.week.cold$Date), FUN = min)

macroclimate.vivarp.cold.meansoil <- aggregate(vivarp.week.cold$era5_soil, by = list(vivarp.week.cold$Date), FUN = mean)

macroclimate.vivarp.cold <- cbind(macroclimate.vivarp.cold.meanair, macroclimate.vivarp.cold.maxair, macroclimate.vivarp.cold.minair, macroclimate.vivarp.cold.meansoil)

macroclimate.vivarp.cold <- macroclimate.vivarp.cold[,c(1,2,4,6, 8)]

names(macroclimate.vivarp.cold) <- c("Date", "mean_era5_air", "max_era5_air", "min_era5_air", "mean_era5_soil")


vivarp.coldplot <- ggplot(macroclimate.vivarp.cold, aes(x = Date)) +
geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 1),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 2),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 3),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 4),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 5),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 6),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 7),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 8),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 9),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 10),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 11),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 12),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 13),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 14),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 15),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 16),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 17),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 18),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 19),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 20),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 21),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 22),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 23),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 24),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 25),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 26),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 27),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 28),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 29),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 31),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 32),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 33),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 34),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 35),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 36),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 37),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 38),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 39),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.cold[which(vivarp.week.cold$Plot == 40),]$loggertemp)) + 
      geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
    geom_line(aes(y = max_era5_air), colour = "dark red", lwd = 2) +
    geom_line(aes(y = min_era5_air), colour = "orange", lwd = 2) +
  ggtitle("Vivarp coldest month")
  
#rm(macroclimate.vivarp.cold)
#rm(vivarp.week.cold)

# Same with warmest month (july):

onewarmweek <- seq(ymd('2021-7-1'),ymd('2021-7-31'), by = '1 d')

vivarp.week.warm <- vivarp[vivarp$Date %in% onewarmweek,]

macroclimate.vivarp.warm.meanair <- aggregate(vivarp.week.warm$era5_air, by = list(vivarp.week.warm$Date), FUN = mean)

macroclimate.vivarp.warm.maxair <- aggregate(vivarp.week.warm$era5_max, by = list(vivarp.week.warm$Date), FUN = max)

macroclimate.vivarp.warm.minair <- aggregate(vivarp.week.warm$era5_min, by = list(vivarp.week.warm$Date), FUN = min)

macroclimate.vivarp.warm.meansoil <- aggregate(vivarp.week.warm$era5_soil, by = list(vivarp.week.warm$Date), FUN = mean)

macroclimate.vivarp.warm <- cbind(macroclimate.vivarp.warm.meanair, macroclimate.vivarp.warm.maxair, macroclimate.vivarp.warm.minair, macroclimate.vivarp.warm.meansoil)

macroclimate.vivarp.warm <- macroclimate.vivarp.warm[,c(1,2,4,6, 8)]

names(macroclimate.vivarp.warm) <- c("Date", "mean_era5_air", "max_era5_air", "min_era5_air", "mean_era5_soil")


vivarp.warmplot <- ggplot(macroclimate.vivarp.warm, aes(x = Date)) +
geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 1),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 2),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 3),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 4),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 5),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 6),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 7),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 8),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 9),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 10),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 11),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 12),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 13),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 14),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 15),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 16),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 17),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 18),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 19),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 20),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 21),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 22),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 23),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 24),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 25),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 26),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 27),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 28),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 29),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 31),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 32),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 33),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 34),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 35),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 36),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 37),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 38),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 39),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= vivarp.week.warm[which(vivarp.week.warm$Plot == 40),]$loggertemp)) + 
      geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
    geom_line(aes(y = max_era5_air), colour = "dark red", lwd = 2) +
    geom_line(aes(y = min_era5_air), colour = "orange", lwd = 2) +
  ggtitle("Vivarp warmest month")

rm(vivarp)
#rm(vivarp.week.warm)
#rm(macroclimate.vivarp.warm)
```

Siljan:

```{r}
siljan <- tree.temp[which(tree.temp$site == "Siljan"),]

siljan <- siljan[which(siljan$location == "a"),]

onecoldweek <- seq(ymd('2021-1-1'),ymd('2021-1-31'), by = '1 d')
siljan$Date <- as.Date(siljan$Date)

siljan.week.cold <- siljan[siljan$Date %in% onecoldweek,]

macroclimate.siljan.cold.meanair <- aggregate(siljan.week.cold$era5_air, by = list(siljan.week.cold$Date), FUN = mean)

macroclimate.siljan.cold.maxair <- aggregate(siljan.week.cold$era5_max, by = list(siljan.week.cold$Date), FUN = max)

macroclimate.siljan.cold.minair <- aggregate(siljan.week.cold$era5_min, by = list(siljan.week.cold$Date), FUN = min)

macroclimate.siljan.cold.meansoil <- aggregate(siljan.week.cold$era5_soil, by = list(siljan.week.cold$Date), FUN = mean)

macroclimate.siljan.cold <- cbind(macroclimate.siljan.cold.meanair, macroclimate.siljan.cold.maxair, macroclimate.siljan.cold.minair, macroclimate.siljan.cold.meansoil)

macroclimate.siljan.cold <- macroclimate.siljan.cold[,c(1,2,4,6, 8)]

names(macroclimate.siljan.cold) <- c("Date", "mean_era5_air", "max_era5_air", "min_era5_air", "mean_era5_soil")

siljan.coldplot <- ggplot(macroclimate.siljan.cold, aes(x = Date)) +
geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 1),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 2),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 3),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 4),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 5),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 6),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 7),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 8),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 9),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 10),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 11),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 13),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 15),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 16),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 17),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 19),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 20),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 22),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 23),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 24),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 25),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 26),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 27),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 28),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 29),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 31),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 32),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 33),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 34),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 35),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 36),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 37),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 38),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 39),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.cold[which(siljan.week.cold$Plot == 40),]$loggertemp)) + 
      geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
    geom_line(aes(y = max_era5_air), colour = "dark red", lwd = 2) +
    geom_line(aes(y = min_era5_air), colour = "orange", lwd = 2) +
  ggtitle("Siljan coldest month")
  
#rm(macroclimate.siljan.cold)
#rm(siljan.week.cold)

# Same with warmest month (july):

onewarmweek <- seq(ymd('2020-7-1'),ymd('2020-7-31'), by = '1 d')

siljan.week.warm <- siljan[siljan$Date %in% onewarmweek,]

macroclimate.siljan.warm.meanair <- aggregate(siljan.week.warm$era5_air, by = list(siljan.week.warm$Date), FUN = mean)

macroclimate.siljan.warm.maxair <- aggregate(siljan.week.warm$era5_max, by = list(siljan.week.warm$Date), FUN = max)

macroclimate.siljan.warm.minair <- aggregate(siljan.week.warm$era5_min, by = list(siljan.week.warm$Date), FUN = min)

macroclimate.siljan.warm.meansoil <- aggregate(siljan.week.warm$era5_soil, by = list(siljan.week.warm$Date), FUN = mean)

macroclimate.siljan.warm <- cbind(macroclimate.siljan.warm.meanair, macroclimate.siljan.warm.maxair, macroclimate.siljan.warm.minair, macroclimate.siljan.warm.meansoil)

macroclimate.siljan.warm <- macroclimate.siljan.warm[,c(1,2,4,6, 8)]

names(macroclimate.siljan.warm) <- c("Date", "mean_era5_air", "max_era5_air", "min_era5_air", "mean_era5_soil")


siljan.warmplot <- ggplot(macroclimate.siljan.warm, aes(x = Date)) +
geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 1),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 2),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 3),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 4),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 5),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 6),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 7),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 8),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 9),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 10),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 11),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 13),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 15),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 16),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 17),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 19),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 20),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 22),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 23),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 24),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 25),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 26),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 27),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 28),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 29),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 31),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 32),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 33),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 34),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 35),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 36),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 37),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 38),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 39),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= siljan.week.warm[which(siljan.week.warm$Plot == 40),]$loggertemp)) + 
      geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
    geom_line(aes(y = max_era5_air), colour = "dark red", lwd = 2) +
    geom_line(aes(y = min_era5_air), colour = "orange", lwd = 2) +
  ggtitle("Hochwald warmest month")

rm(siljan)
#rm(siljan.week.warm)
#rm(macroclimate.siljan.warm)
```

Sandsj:

```{r}
sandsjo <- tree.temp[which(tree.temp$site == "Sandsjo"),]

sandsjo <- sandsjo[which(sandsjo$location == "a"),]

onecoldweek <- seq(ymd('2020-1-1'),ymd('2020-1-31'), by = '1 d')
sandsjo$Date <- as.Date(sandsjo$Date)

sandsjo.week.cold <- sandsjo[sandsjo$Date %in% onecoldweek,]

macroclimate.sandsjo.cold.meanair <- aggregate(sandsjo.week.cold$era5_air, by = list(sandsjo.week.cold$Date), FUN = mean)

macroclimate.sandsjo.cold.maxair <- aggregate(sandsjo.week.cold$era5_max, by = list(sandsjo.week.cold$Date), FUN = max)

macroclimate.sandsjo.cold.minair <- aggregate(sandsjo.week.cold$era5_min, by = list(sandsjo.week.cold$Date), FUN = min)

macroclimate.sandsjo.cold.meansoil <- aggregate(sandsjo.week.cold$era5_soil, by = list(sandsjo.week.cold$Date), FUN = mean)

macroclimate.sandsjo.cold <- cbind(macroclimate.sandsjo.cold.meanair, macroclimate.sandsjo.cold.maxair, macroclimate.sandsjo.cold.minair, macroclimate.sandsjo.cold.meansoil)

macroclimate.sandsjo.cold <- macroclimate.sandsjo.cold[,c(1,2,4,6, 8)]

names(macroclimate.sandsjo.cold) <- c("Date", "mean_era5_air", "max_era5_air", "min_era5_air", "mean_era5_soil")


sandsjo.coldplot <- ggplot(macroclimate.sandsjo.cold, aes(x = Date)) +
geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 1),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 2),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 3),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 4),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 5),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 6),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 7),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 8),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 9),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 10),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 11),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 12),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 13),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 14),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 15),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 16),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 17),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 18),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 19),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 21),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 22),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 23),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 24),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 25),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 26),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 27),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 28),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 29),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 30),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 31),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 32),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 33),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 34),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 35),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 36),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 38),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 39),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.cold[which(sandsjo.week.cold$Plot == 40),]$loggertemp)) + 
      geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
    geom_line(aes(y = max_era5_air), colour = "dark red", lwd = 2) +
    geom_line(aes(y = min_era5_air), colour = "orange", lwd = 2) +
  ggtitle("Sandsj coldest month")

#rm(macroclimate.sandsjo.cold)
#rm(sandsjo.week.cold)

# Same with warmest month (july):

onewarmweek <- seq(ymd('2020-7-1'),ymd('2020-7-31'), by = '1 d')

sandsjo.week.warm <- sandsjo[sandsjo$Date %in% onewarmweek,]

macroclimate.sandsjo.warm.meanair <- aggregate(sandsjo.week.warm$era5_air, by = list(sandsjo.week.warm$Date), FUN = mean)

macroclimate.sandsjo.warm.maxair <- aggregate(sandsjo.week.warm$era5_max, by = list(sandsjo.week.warm$Date), FUN = max)

macroclimate.sandsjo.warm.minair <- aggregate(sandsjo.week.warm$era5_min, by = list(sandsjo.week.warm$Date), FUN = min)

macroclimate.sandsjo.warm.meansoil <- aggregate(sandsjo.week.warm$era5_soil, by = list(sandsjo.week.warm$Date), FUN = mean)

macroclimate.sandsjo.warm <- cbind(macroclimate.sandsjo.warm.meanair, macroclimate.sandsjo.warm.maxair, macroclimate.sandsjo.warm.minair, macroclimate.sandsjo.warm.meansoil)

macroclimate.sandsjo.warm <- macroclimate.sandsjo.warm[,c(1,2,4,6, 8)]

names(macroclimate.sandsjo.warm) <- c("Date", "mean_era5_air", "max_era5_air", "min_era5_air", "mean_era5_soil")


sandsjo.warmplot <- ggplot(macroclimate.sandsjo.warm, aes(x = Date)) +
geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 1),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 2),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 3),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 4),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 5),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 6),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 7),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 8),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 9),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 10),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 11),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 12),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 13),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 14),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 15),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 16),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 17),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 18),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 19),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 21),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 22),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 23),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 24),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 25),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 26),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 27),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 28),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 29),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 30),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 31),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 32),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 33),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 34),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 35),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 36),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 38),]$loggertemp)) +
    geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 39),]$loggertemp)) +
  geom_line(color = "gray45", alpha = 0.5, lwd = 1, aes(y= sandsjo.week.warm[which(sandsjo.week.warm$Plot == 40),]$loggertemp)) + 
      geom_line(aes(y = mean_era5_air), colour = "red", lwd = 2) +
    geom_line(aes(y = max_era5_air), colour = "dark red", lwd = 2) +
    geom_line(aes(y = min_era5_air), colour = "orange", lwd = 2) +
  ggtitle("Sandsj warmest month")

rm(sandsjo)
#rm(sandsjo.week.warm)
#rm(macroclimate.sandsjo.warm)

rm(onecoldweek)
rm(onewarmweek)

rm(tree.temp)
```


```{r}
library(gridExtra)

grid.arrange(arville.coldplot,
arville.warmplot,
hochwald.coldplot,
hochwald.warmplot,
vivarp.coldplot,
vivarp.warmplot,
siljan.coldplot,
siljan.warmplot,
sandsjo.coldplot,
sandsjo.warmplot, ncol=2)
```