# Offset calculation and dataset merging

First, we need to load ERA5 data and logger data:

```{r}
logger.temp <- read.csv("./DATASETS/logger_temp.csv", header = TRUE)

ERA5.temp <- read.csv("./DATASETS/ERA5_temp.csv", header = TRUE)
```

###############
Calculate mean temperature and precipitation for the five previous days

```{r}
library(dplyr)
library(zoo)

ERA5.temp <- ERA5.temp %>%
    dplyr::arrange(Date) %>% 
    dplyr::arrange(desc(site)) %>% 
    dplyr::group_by(site) %>% 
    dplyr::mutate(prev_av_temp = lag(zoo::rollmean(era5_air, 
                                               k = 5, 
                                               fill = NA), n = 3)) %>% 
  dplyr::ungroup()

ERA5.temp <- ERA5.temp %>%
    dplyr::arrange(Date) %>% 
    dplyr::arrange(desc(site)) %>% 
    dplyr::group_by(site) %>% 
    dplyr::mutate(prev_av_prec = lag(zoo::rollmean(prec, 
                                               k = 5, 
                                               fill = NA), n = 3)) %>% 
  dplyr::ungroup()
```

###############


And we merge them by site and date:

```{r}
temp <- merge(logger.temp, ERA5.temp, by = c("site", "Date"))

rm(logger.temp)
rm(ERA5.temp)
```

Calculate temperature offsets:

```{r}
temp$air_off <- temp$Temp.mean - temp$era5_air # air mean temperature

temp[which(temp$location == "s"),]$air_off <- NA # knock out values for soil loggers, as this will be calculated with "era5_soil"

temp$min_off <- temp$Temp.min - temp$era5_min

temp[which(temp$location == "s"),]$min_off <- NA # remove minimum values for soil temperature, as offsets are calculated with minimum air temperature.

temp$max_off <- temp$Temp.max - temp$era5_max

temp[which(temp$location == "s"),]$max_off <- NA # remove maximum values for soil temperature, as offsets are calculated with minimum air

temp$soil_off <- temp$Temp.mean-temp$era5_soil

temp[which(temp$location == "a"),]$soil_off <- NA # remove values obtained for air loggers, as offsets have been calculated with soil temperature
```

# Merge with tree data

Load tree data:

```{r}
tree.data <- read.csv("./DATASETS/tree_data.csv", header = TRUE)
```

Merge the temperature dataset and the tree data:

```{r}
tree.temp <- merge(temp, tree.data, by = c("site", "Plot"))

rm(temp)
rm(tree.data)
```

Export the merged dataset:

```{r}
write.csv(tree.temp, file = "./DATASETS/tree_temp.csv", row.names = FALSE, quote = FALSE)

rm(list = ls())
```